// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndnnybeztyaytdtpsqhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kbm55YmV6dHlheXRkdHBzcWhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1MTk1MzQsImV4cCI6MjA2NTA5NTUzNH0.UaZGrcDdInNUBwQz9KHsT_AeQJcOuMFtlaOmr9cJ6vc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);